// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFPbH4RCdVzLsdoKJqi0R-5qeApynrwYI',
    appId: '1:694826758088:web:364f94edb6decd5aca1afd',
    messagingSenderId: '694826758088',
    projectId: 'backend-24124',
    authDomain: 'backend-24124.firebaseapp.com',
    storageBucket: 'backend-24124.firebasestorage.app',
    measurementId: 'G-5GNFK20ZCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjbfxfsyssQoHVJa_tpEjhH8X7RnSDUrc',
    appId: '1:694826758088:android:6d77c0be500566bdca1afd',
    messagingSenderId: '694826758088',
    projectId: 'backend-24124',
    storageBucket: 'backend-24124.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwbid6U8moyAK-wi7Cgf4lOBFa_bNUO1w',
    appId: '1:694826758088:ios:ac69b92257fdbabbca1afd',
    messagingSenderId: '694826758088',
    projectId: 'backend-24124',
    storageBucket: 'backend-24124.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwbid6U8moyAK-wi7Cgf4lOBFa_bNUO1w',
    appId: '1:694826758088:ios:ac69b92257fdbabbca1afd',
    messagingSenderId: '694826758088',
    projectId: 'backend-24124',
    storageBucket: 'backend-24124.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFPbH4RCdVzLsdoKJqi0R-5qeApynrwYI',
    appId: '1:694826758088:web:3c199ab26ac40043ca1afd',
    messagingSenderId: '694826758088',
    projectId: 'backend-24124',
    authDomain: 'backend-24124.firebaseapp.com',
    storageBucket: 'backend-24124.firebasestorage.app',
    measurementId: 'G-7KQVJME6DX',
  );
}
