name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons for iOS
  cupertino_icons: ^1.0.8

  # HTTP package to handle network requests
  http: ^0.13.3

  # State management package
  provider: ^6.0.5

  # For form validation and handling
  flutter_form_builder: ^7.5.0

  # For JSON serialization/deserialization
  json_serializable: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.2.0 # Required for code generation (e.g., json_serializable)

flutter:
  uses-material-design: true
